MicrosoftDocs/globalization

globalization/locale/sorting-and-string-comparison.md
Added section on "How do I verify that sorting works correctly in my code?". This will make it easier for people who use existing framework to validate that the code does not contain trivial errors such as passing using a wrong locale with string comparison functions.
=> Added info on how to test sorting

globalization/docfx.json, globalization/index.md
=> merge to live

globalization/design/internationalization.md
Minor changes to several lines in the internationalization.md file.
=> Minor Grammatical Changes to docs

globalization/localization/ministyleguides/mini-style-guide-german.md
Updated text to be consistent with other style guides
=> Updated examples and a few other small issues

globalization/localization/ministyleguides/mini-style-guide-spanish-neutral.md, globalization/localization/styleguides.md
Add Spanish Neutral Quick Start Style Guide
=> Add Spanish Neutral Quick Start Style Guide

globalization/locale/number-formatting-in-win32.md
For issue https://github.com/MicrosoftDocs/feedback/issues/1964
=> remove backslash on underscores

globalization/downloads.md
The previous link didn’t lead anywhere anymore. Let me know if there is a better link than this and I’ll amend the patch.
=> Update link to Multilingual App Toolkit

globalization/design/international-laws-and-standards.md, globalization/downloads.md, globalization/input/ensure-that-the-application-is-fully-unicode-enabled.md, globalization/input/keyboards.md, globalization/input/overlay.md, globalization/input/text-justification.md, globalization/locale/browser-language-setting.md, globalization/locale/currency-formatting-in-the-dotnet-framework.md, globalization/locale/currency-formatting-in-win32.md, globalization/locale/handling-calendars-in-dotnet-framework.md, globalization/locale/handling-calendars-in-win32.md, globalization/locale/number-formatting-in-dotnet-framework.md, globalization/locale/number-formatting-in-win32.md, globalization/locale/time-formatting-and-time-zones-in-dotnet-framework.md, globalization/locale/time-formatting-and-time-zones-in-win32.md, globalization/localizability/avoid-run-time-composite-strings.md, globalization/localizability/do-not-compound-several-variables.md, globalization/localizability/dotnet-framework-string-format.md, globalization/localizability/keep-sentences-in-a-single-string.md, globalization/localizability/watch-your-string-buffer-sizes.md, globalization/localizability/when-variables-are-necessary.md, globalization/localizability/win32-formatmessage.md, globalization/localization/build-process-and-packaging.md, globalization/localization/fonts.md, globalization/localization/graphics-and-multimedia.md, globalization/localization/keyboard-shortcuts.md, globalization/localization/layout.md
Automatically cleaned with Docs Authoring Pack cleanup action in VS Code
=> chore: remove empty metadata

globalization/localization/ministyleguides/mini-style-guide-russian.md
=> Typo fix in mini-style-guide-russian.md

globalization/keyboards/kbduk.html, globalization/keyboards/kbdukx.html
To address https://github.com/MicrosoftDocs/globalization/issues/158
=> Updated UK keyboards for full-height Enter key

globalization/design/international-laws-and-standards.md
=> Updated references for GDPR

globalization/localization/ministyleguides/mini-style-guide-czech.md, globalization/localization/ministyleguides/mini-style-guide-german.md, globalization/localization/ministyleguides/mini-style-guide-italian.md, globalization/localization/ministyleguides/mini-style-guide-polish.md, globalization/localization/ministyleguides/mini-style-guide-portuguese-brazil.md, globalization/localization/ministyleguides/mini-style-guide-russian.md, globalization/localization/ministyleguides/mini-style-guide-spanish-neutral.md
=> Fixed broken links per @DhurataJ

globalization/encoding/char0067.html, globalization/encoding/char845B.html, globalization/encoding/char845BVS17.html, globalization/encoding/surrogate-pairs.md
Based on work by @Porges.
As we can no longer use inline styling, we'll need to use standalone HTML files to style characters.
=> Surrogate pair characters (#237)

globalization/locale/fallback.md, globalization/locale/standard-locale-names.md
This PR addresses the following Policheck bugs:
- https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/121215
- https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/121219
- https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/121223
=> Policheck update - July 20 | Bulk Update

globalization/internationalization/international-laws-and-standards.md, globalization/locale/other-locale-names.md, globalization/locale/sorting-and-string-comparison.md, globalization/localizability/images-and-icons.md
This PR addresses the following Policheck bug:
- https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109053
- https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109055
- https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109058
- https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109066
=> Policheck update - August 9 | Bulk Update

.openpublishing.redirection.json
=> Missing path

globalization/internationalization/payment-methods.md, globalization/locale/language-settings.md, globalization/locale/system-user-settings.md, globalization/toc.yml
=> Systems and user settings & Payment methods added.

globalization/methodology/how-to-validate-internationalized-products.md, globalization/testing/how-to-test-internationalized-products.md, globalization/testing/how-to-test.md, globalization/testing/validating-products-for-international-release.md, globalization/testing/what-to-look-for-when-testing.md, globalization/testing/when-to-test.md, globalization/toc.yml
Updated localizability testing and localization testing articles and TOC.
=> Validation articles

globalization/index.yml, globalization/input/japanese-ime.md, globalization/localization/localization-overview.md, globalization/methodology/global-product-delivery.md, globalization/methodology/international-design.md, globalization/methodology/software-internationalization.md
=> SEO improvements for learn.microsoft

globalization/localization/localization-overview.md, globalization/localization/localize-software.md
Edited to prepare for being featured in social media.
=> Edits to localization-overview.md

globalization/methodology/global-product-delivery.md
Edited this topic in prep for featuring it on social media.
=> Edits to global-product-delivery.md

globalization/input/odia-ime.md
This PR resolves the following Policheck issues:
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/307324
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/307332
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/307313
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/307345
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/307323
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/307302
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/307330
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/307312
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/30 …
=> Policheck Update - April 7 | Bulk Update
